### ISSUE TITLE
CSS in imported SASS files is not auto-prefixed

### ISSUE THREAD

**Issue by btjanaka** [stowball/elf#2]
I noticed that if one creates a file such as `_foo.scss`:

```css
html {
  display: flex;
}
```

And `index.scss`:

```
@import "foo";
```

Then in `dist/assets/main.css`, `display: flex`is not auto-prefixed. However, if you put the same snippet from `_foo.scss` into `index.scss`, it is properly auto-prefixed. Do you where this issue may be coming from, or if it is an expected feature? Thanks!

**Comment by stowball** [comment]
Hmmmm let me investigate…

**Comment by btjanaka** [comment]
Thanks! Looks like it works for me.

**Comment by stowball** [comment]
Whoop whoop. Thanks so much for finding this issue. It's so easy to overlook things like this with such a bare-bones project
